name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Instalar dependências para a API
        run: |
          cd Apps/api
          rm -rf node_modules
          [ -f package-lock.json ] && rm package-lock.json
          yarn install --ignore-scripts
          yarn add better-sqlite3 --build-from-source

      - name: Instalar dependências para o Web
        run: |
          cd Apps/web
          rm -rf node_modules
          [ -f package-lock.json ] && rm package-lock.json
          yarn install

      - name: Iniciar API em segundo plano
        run: |
          cd Apps/api
          yarn dev &
          sleep 5

      - name: Iniciar Web em segundo plano
        run: |
          cd Apps/web
          yarn dev &
          sleep 5
          
      - name: Instalar dependências para testes
        run: |
          yarn install
          yarn add cypress --dev
          yarn cypress install

      - name: Rodar testes no Cypress
        run: |
          yarn cypress run

      - name: Upload de screenshots e vídeos em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: cypress/screenshots/, cypress/videos/
