name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Restaurar cache das dependências da API
        uses: actions/cache@v4
        with:
          path: Apps/api/node_modules
          key: ${{ runner.os }}-api-node-${{ hashFiles('Apps/api/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-api-node-

      - name: Restaurar cache das dependências do Web
        uses: actions/cache@v4
        with:
          path: Apps/web/node_modules
          key: ${{ runner.os }}-web-node-${{ hashFiles('Apps/web/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-web-node-

      - name: Instalar dependências para a API
        run: |
          cd Apps/api
          yarn install --ignore-scripts
          yarn add better-sqlite3 --build-from-source

      - name: Instalar dependências para o Web
        run: |
          cd Apps/web
          yarn install

      - name: Iniciar API e Web
        run: |
          cd Apps/api && yarn dev & api_pid=$!
          cd ../web && yarn dev & web_pid=$!
          sleep 5
          trap "kill $api_pid $web_pid" EXIT

      - name: Instalar dependências para testes
        run: |
          yarn install
          yarn add cypress --dev
          yarn cypress install

      - name: Rodar testes no Cypress (com paralelismo)
        run: |
          yarn cypress run --record --parallel
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload de screenshots e vídeos em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: cypress/screenshots/, cypress/videos/

      - name: Gerar relatório de testes
        run: |
          yarn cypress run --reporter junit --reporter-options "mochaFile=results/junit/test-results.xml"

      - name: Publicar relatório de testes
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-results
          path: results/junit/
